# Custom Language File for Launcher Customizer

[ejs.app]
title = "Random-Community Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Patrick15a/Random-Community-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Patrick15a/Random-Community-Launcher"
supportLink = "https://github.com/Patrick15a/Random-Community-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Willkommen"
welcomeDescription = "Dies ist der Modpack Launcher von Random-Community.de und BexoGames.de"
welcomeDescCTA = "Wähle dein Modpack und los gehts"
