[ejs.landing]
updateAvailableTooltip = "Update Verfügbar"
usernamePlaceholder = "Benutzername"
usernameEditButton = "Bearbeiten"
settingsTooltip = "Einstellungen"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Dienste"
mojangStatusNETitle = "Nicht&nbsp;Essentiell"
newsButton = "NEWS"
launchButton = "Spielen"
launchButtonPlaceholder = "&#8226; Kein Server ausgewählt"
launchDetails = "Bitte warten.."
newsNavigationStatus = "{currentPage} von {totalPages}"
newsErrorLoadSpan = "Suche nach Neuigkeiten.."
newsErrorFailedSpan = "Laden der News fehlgeschlagen"
newsErrorRetryButton = "Erneut versuchen"
newsErrorNoneSpan = "Keine Neuigkeiten"

[ejs.login]
loginCancelText = "Abbrechen"
loginSubheader = "MINECRAFT ANMELDUNG"
loginEmailError = "* Ungültiger Wert"
loginEmailPlaceholder = "E-MAIL ODER BENUTZERNAME"
loginPasswordError = "* Erforderlich"
loginPasswordPlaceholder = "PASSWORT"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Passwort vergessen?"
loginRememberMeText = "Angemeldet bleiben?"
loginButtonText = "ANMELDEN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Konto erstellen?"
loginPasswordDisclaimer1 = "Dein Passwort wird direkt an Mojang gesendet und nie gespeichert."
loginPasswordDisclaimer2 = "{appName} ist nicht mit Mojang AB verbunden."

[ejs.loginOptions]
loginOptionsTitle = "Anmeldeoptionen"
loginWithMicrosoft = "Mit Microsoft anmelden"
loginWithMojang = "Mit Mojang anmelden"
cancelButton = "Abbrechen"

[ejs.overlay]
serverSelectHeader = "Verfügbare Server"
serverSelectConfirm = "Auswählen"
serverSelectCancel = "Abbrechen"
accountSelectHeader = "Konto auswählen"
accountSelectConfirm = "Auswählen"
accountSelectCancel = "Abbrechen"

[ejs.settings]
closeLauncherOnLaunchTitle = "Launcher schließen, wenn das Spiel startet."
closeLauncherOnLaunchDesc = "Funktioniert nur mit aktivierter Option \"Spielprozess vom Launcher getrennt starten\"."
navHeaderText = "Einstellungen"
navAccount = "Konto"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Über"
navUpdates = "Updates"
navDone = "Fertig"
tabAccountHeaderText = "Kontoeinstellungen"
tabAccountHeaderDesc = "Neue Konten hinzufügen oder bestehende verwalten."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Microsoft-Konto hinzufügen"
mojangAccount = "Mojang"
addMojangAccount = "+ Mojang-Konto hinzufügen"
minecraftTabHeaderText = "Minecraft-Einstellungen"
minecraftTabHeaderDesc = "Optionen zum Spielstart."
gameResolutionTitle = "Spielauflösung"
launchFullscreenTitle = "Im Vollbildmodus starten."
autoConnectTitle = "Beim Start automatisch mit dem Server verbinden."
launchDetachedTitle = "Spielprozess vom Launcher getrennt starten."
launchDetachedDesc = "Wenn das Spiel nicht getrennt ist, wird das Spiel beim Schließen des Launchers ebenfalls beendet."
tabModsHeaderText = "Mod-Einstellungen"
tabModsHeaderDesc = "Mods aktivieren oder deaktivieren."
switchServerButton = "Wechseln"
requiredMods = "Erforderliche Mods"
optionalMods = "Optionale Mods"
dropinMods = "Drop-in Mods"
addMods = "Mods hinzufügen"
dropinRefreshNote = "(F5 zum Aktualisieren)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Shader aktivieren oder deaktivieren. Bitte beachte, dass Shader nur auf leistungsstarken Systemen flüssig laufen. Du kannst hier eigene Packs hinzufügen."
selectShaderpack = "Shaderpack auswählen"
tabJavaHeaderText = "Java-Einstellungen"
tabJavaHeaderDesc = "Java-Konfiguration verwalten (fortgeschritten)."
memoryTitle = "Arbeitsspeicher"
maxRAM = "Maximaler RAM"
minRAM = "Minimaler RAM"
memoryDesc = "Der empfohlene Mindest-RAM beträgt 3 Gigabyte. Das Setzen des minimalen und maximalen Wertes auf denselben Wert kann Verzögerungen reduzieren."
memoryTotalTitle = "Gesamt"
memoryAvailableTitle = "Verfügbar"
javaExecutableTitle = "Java-Programmdatei"
javaExecSelDialogTitle = "Java-Programmdatei auswählen"
javaExecSelButtonText = "Datei wählen"
javaExecDesc = "Die Java-Programmdatei wird vor dem Spielstart überprüft."
javaPathDesc = "Der Pfad sollte mit <strong>{pathSuffix}</strong> enden."
jvmOptsTitle = "Zusätzliche JVM-Optionen"
jvmOptsDesc = "Optionen, die der JVM zur Laufzeit übergeben werden. <em>-Xms</em> und <em>-Xmx</em> sollten nicht enthalten sein."
launcherTabHeaderText = "Launcher-Einstellungen"
launcherTabHeaderDesc = "Optionen für den Launcher selbst."
allowPrereleaseTitle = "Vorabversions-Updates erlauben."
allowPrereleaseDesc = "Vorabversionen enthalten neue Funktionen, die möglicherweise noch nicht vollständig getestet oder integriert wurden.<br>Dies ist immer aktiv, wenn du eine Vorabversion verwendest."
dataDirectoryTitle = "Datenverzeichnis"
selectDataDirectory = "Datenverzeichnis auswählen"
chooseFolder = "Ordner auswählen"
dataDirectoryDesc = "Alle Spieldateien und lokale Java-Installationen werden im Datenverzeichnis gespeichert.<br>Screenshots und Welten werden im Instanzordner der entsprechenden Serverkonfiguration gespeichert."
aboutTabHeaderText = "Über"
aboutTabHeaderDesc = "Informationen und Versionshinweise für die aktuelle Version anzeigen."
aboutTitle = "{appName}"
stableRelease = "Stabile Version"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotesFull = "Alle Versionshinweise anzeigen."
resourcePackTextFull = "Ressourcenpaket-Änderungen"
javaOptionsTextFull = "Java-Optionen"
shaderPackTextFull = "Shader-Paket-Änderungen"
modsTextFull = "Mod-Änderungen"

# Metrics drops version text:
#    Beta 5.3.1 (4 June 2023)
#    Total user accounts: 1,014
metricsText1 = "{version} ({date})"
metricsText2 = "Gesamtanzahl der Benutzerkonten: {userCount}"

releaseNotes = "Versionshinweise"
changelog = "Changelog"
noReleaseNotes = "Keine Versionshinweise"
viewReleaseNotes = "Versionshinweise auf GitHub anzeigen"
launcherUpdatesHeaderText = "Launcher-Updates"
launcherUpdatesHeaderDesc = "Updates für den Launcher herunterladen, installieren und überprüfen."
checkForUpdates = "Nach Updates suchen"
whatsNew = "Was ist neu"
updateReleaseNotes = "Update-Versionshinweise"

[ejs.waiting]
waitingText = "Waiting for Microsoft.."

[ejs.welcome]
continueButton = "CONTINUE"


[js.discord]
waiting = "Warte auf Client.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft-Anmeldung"
microsoftLogoutTitle = "Microsoft-Abmeldung"

[js.login]
login = "ANMELDEN"
loggingIn = "ANMELDUNG LÄUFT"
success = "ERFOLGREICH"
tryAgain = "Erneut versuchen"

[js.login.error]
invalidValue = "* Ungültiger Wert"
requiredValue = "* Erforderlich"

[js.login.error.unknown]
title = "Unbekannter Fehler bei der Anmeldung"
desc = "Ein unbekannter Fehler ist aufgetreten. Bitte siehe Konsole für Details."

[js.landing.launch]
pleaseWait = "Bitte warten.."
failureTitle = "Fehler beim Start"
failureText = "Siehe Konsole (STRG + Umschalt + i) für weitere Details."
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Kein Konto ausgewählt"

[js.landing.selectedServer]
noSelection = "Kein Server ausgewählt"
loading = "Lädt.."

[js.landing.serverStatus]
server = "SERVER"
offline = "OFFLINE"
players = "SPIELER"

[js.landing.systemScan]
checking = "Prüfe Systeminformationen.."
noCompatibleJava = "Keine kompatible<br>Java-Installation gefunden"
installJavaMessage = "Um Minecraft zu starten, benötigst du eine 64-Bit-Installation von Java {major}. Möchtest du, dass wir eine Kopie installieren?"
installJava = "Java installieren"
installJavaManually = "Manuell installieren"
javaDownloadPrepare = "Bereite Java-Download vor.."
javaDownloadFailureTitle = "Fehler beim Java-Download"
javaDownloadFailureText = "Siehe Konsole (STRG + Umschalt + i) für weitere Details."
javaRequired = "Java ist zum Start<br>erforderlich"
javaRequiredMessage = 'Eine gültige x64-Installation von Java {major} ist zum Start erforderlich.<br><br>Bitte siehe unseren <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java-Management-Leitfaden</a> für Anweisungen zur manuellen Installation von Java.'
javaRequiredDismiss = "Ich verstehe"
javaRequiredCancel = "Zurück"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK-Distribution konnte nicht gefunden werden."
javaDownloadCorruptedError = "Heruntergeladenes JDK hat einen falschen Hash, die Datei könnte beschädigt sein."
extractingJava = "Extrahiere Java"
javaInstalled = "Java installiert!"

[js.landing.dlAsync]
loadingServerInfo = "Lade Serverinformationen.."
fatalError = "Schwerwiegender Fehler"
unableToLoadDistributionIndex = "Konnte keine Kopie des Verteilungsindex laden. Siehe Konsole (STRG + Umschalt + i) für weitere Details."
pleaseWait = "Bitte warten.."
errorDuringLaunchTitle = "Fehler beim Start"
seeConsoleForDetails = "Siehe Konsole (STRG + Umschalt + i) für weitere Details."
validatingFileIntegrity = "Überprüfe Dateiintegrität.."
errorDuringFileVerificationTitle = "Fehler bei der Dateiüberprüfung"
downloadingFiles = "Lade Dateien herunter.."
errorDuringFileDownloadTitle = "Fehler beim Dateidownload"
preparingToLaunch = "Bereite Start vor.."
launchingGame = "Starte Spiel.."
launchWrapperNotDownloaded = "Die Hauptdatei, LaunchWrapper, konnte nicht korrekt heruntergeladen werden. Daher kann das Spiel nicht gestartet werden.<br><br>Um dieses Problem zu beheben, deaktiviere vorübergehend deine Antivirensoftware und starte das Spiel erneut.<br><br>Wenn du Zeit hast, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">erstelle bitte ein Issue</a> und lass uns wissen, welche Antivirensoftware du verwendest. Wir werden sie kontaktieren und versuchen, das Problem zu lösen."
doneEnjoyServer = "Fertig. Viel Spaß auf dem Server!"
checkConsoleForDetails = "Bitte prüfe die Konsole (STRG + Umschalt + i) für weitere Details."

[js.landing.news]
checking = "Suche nach Neuigkeiten"

[js.landing.discord]
loading = "Lade Spiel.."
joining = "Reise nach Westeros!"
joined = "Erkunde das Reich!"

[js.overlay]
dismiss = "Schließen"

[js.settings.fileSelectors]
executables = "Ausführbare Dateien"
allFiles = "Alle Dateien"

[js.settings.mstfLogin]
errorTitle = "Etwas ist schief gelaufen"
errorMessage = "Microsoft-Authentifizierung fehlgeschlagen. Bitte versuche es erneut."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Etwas ist schief gelaufen"
errorMessage = "Microsoft-Abmeldung fehlgeschlagen. Bitte versuche es erneut."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Konto auswählen"
selectedButton = "Ausgewähltes Konto &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Warnung<br>Dies ist dein letztes Konto"
lastAccountWarningMessage = "Um den Launcher zu nutzen, musst du mit mindestens einem Konto angemeldet sein. Du musst dich danach erneut anmelden.<br><br>Bist du sicher, dass du dich abmelden möchtest?"
confirmButton = "Ich bin sicher"
cancelButton = "Abbrechen"

[js.settings.authAccountPopulate]
username = "Benutzername"
uuid = "UUID"
selectAccount = "Konto auswählen"
selectedAccount = "Ausgewähltes Konto ✓"
logout = "Abmelden"

[js.settings.dropinMods]
removeButton = "Entfernen"
deleteFailedTitle = "Löschen fehlgeschlagen<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Stelle sicher, dass die Datei nicht verwendet wird und versuche es erneut."
failedToggleTitle = "Aktivierung fehlgeschlagen<br>Eine oder mehrere Drop-in Mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Hauptserver"

[js.settings.java]
selectedJava = "Ausgewählt: Java {version} ({vendor})"
invalidSelection = "Ungültige Auswahl"
requiresJava = "Benötigt Java {major} x64."
availableOptions = "Verfügbare Optionen für Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Vorabversion"
stableReleaseTitle = "Stabile Version"
releaseNotesFailed = "Versionshinweise konnten nicht geladen werden."

[js.settings.updates]
newReleaseTitle = "Neue Version verfügbar"
newPreReleaseTitle = "Neue Vorabversion verfügbar"
downloadingButton = "Wird heruntergeladen.."
downloadButton = 'Von GitHub herunterladen<span style="font-size: 10px;color: gray;text-shadow: none !important;">Schließe den Launcher und führe die dmg-Datei aus, um zu aktualisieren.</span>'
latestVersionTitle = "Du verwendest die neueste Version"
checkForUpdatesButton = "Nach Updates suchen"
checkingForUpdatesButton = "Suche nach Updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft-Anmeldung fehlgeschlagen"
errorMessage = "Wir konnten dein Microsoft-Konto nicht authentifizieren. Bitte versuche es erneut."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Schwerwiegender Fehler: Verteilungsindex konnte nicht geladen werden"
fatalErrorMessage = "Es konnte keine Verbindung zu unseren Servern hergestellt werden, um den Verteilungsindex herunterzuladen. Keine lokalen Kopien zum Laden verfügbar. <br><br>Der Verteilungsindex ist eine wichtige Datei, die die neuesten Serverinformationen enthält. Der Launcher kann ohne sie nicht gestartet werden. Stelle sicher, dass du mit dem Internet verbunden bist und starte die Anwendung neu."
closeButton = "Schließen"

[js.uibinder.validateAccount]
failedMessageTitle = "Anmeldung konnte nicht aktualisiert werden"
failedMessage = "Wir konnten die Anmeldung für <strong>{account}</strong> nicht aktualisieren. Bitte wähle ein anderes Konto aus oder melde dich erneut an."
failedMessageSelectAnotherAccount = "Wir konnten die Anmeldung für <strong>{account}</strong> nicht aktualisieren. Bitte melde dich erneut an."
loginButton = "Anmelden"
selectAnotherAccountButton = "Anderes Konto auswählen"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Suche nach Updates..."
installNowButton = "Jetzt installieren"
checkForUpdatesButton = "Nach Updates suchen"

[js.auth.microsoft.error]
noProfileTitle = "Fehler bei der Anmeldung:<br>Profil nicht eingerichtet"
noProfileDesc = "Dein Microsoft-Konto hat noch kein Minecraft-Profil eingerichtet. Wenn du das Spiel kürzlich gekauft oder über Xbox Game Pass eingelöst hast, musst du dein Profil auf <a href=\"https://minecraft.net/\">Minecraft.net</a> einrichten.<br><br>Wenn du das Spiel noch nicht gekauft hast, kannst du das auch auf <a href=\"https://minecraft.net/\">Minecraft.net</a> tun."
noXboxAccountTitle = "Fehler bei der Anmeldung:<br>Kein Xbox-Konto"
noXboxAccountDesc = "Dein Microsoft-Konto hat kein zugehöriges Xbox-Konto."
xblBannedTitle = "Fehler bei der Anmeldung:<br>Xbox Live nicht verfügbar"
xblBannedDesc = "Dein Microsoft-Konto stammt aus einem Land, in dem Xbox Live nicht verfügbar oder gesperrt ist."
under18Title = "Fehler bei der Anmeldung:<br>Elterliche Freigabe erforderlich"
under18Desc = "Konten für Benutzer unter 18 Jahren müssen von einem Erwachsenen zu einer Familie hinzugefügt werden."
unknownTitle = "Unbekannter Fehler bei der Anmeldung"
unknownDesc = "Ein unbekannter Fehler ist aufgetreten. Bitte siehe Konsole für Details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Interner Fehler:<br>Methode nicht erlaubt"
methodNotAllowedDesc = "Methode nicht erlaubt. Bitte melde diesen Fehler."
notFoundTitle = "Interner Fehler:<br>Nicht gefunden"
notFoundDesc = "Der Authentifizierungsendpunkt wurde nicht gefunden. Bitte melde dieses Problem."
accountMigratedTitle = "Fehler bei der Anmeldung:<br>Konto migriert"
accountMigratedDesc = "Du hast versucht, dich mit einem migrierten Konto anzumelden. Versuche es erneut mit der E-Mail-Adresse des Kontos als Benutzernamen."
invalidCredentialsTitle = "Fehler bei der Anmeldung:<br>Ungültige Anmeldedaten"
invalidCredentialsDesc = "Die eingegebene E-Mail-Adresse oder das Passwort ist falsch. Bitte versuche es erneut."
tooManyAttemptsTitle = "Fehler bei der Anmeldung:<br>Zu viele Versuche"
tooManyAttemptsDesc = "Es gab kürzlich zu viele Anmeldeversuche mit diesem Konto. Bitte versuche es später erneut."
invalidTokenTitle = "Fehler bei der Anmeldung:<br>Ungültiges Token"
invalidTokenDesc = "Das bereitgestellte Zugriffstoken ist ungültig."
tokenHasProfileTitle = "Fehler bei der Anmeldung:<br>Token hat Profil"
tokenHasProfileDesc = "Zugriffstoken hat bereits ein zugewiesenes Profil. Die Profilauswahl ist noch nicht implementiert."
credentialsMissingTitle = "Fehler bei der Anmeldung:<br>Anmeldedaten fehlen"
credentialsMissingDesc = "Benutzername/Passwort wurde nicht übermittelt oder das Passwort hat weniger als 3 Zeichen."
invalidSaltVersionTitle = "Fehler bei der Anmeldung:<br>Ungültige Salt-Version"
invalidSaltVersionDesc = "Ungültige Salt-Version."
unsupportedMediaTypeTitle = "Interner Fehler:<br>Nicht unterstützter Medientyp"
unsupportedMediaTypeDesc = "Nicht unterstützter Medientyp. Bitte melde diesen Fehler."
accountGoneTitle = "Fehler bei der Anmeldung:<br>Konto migriert"
accountGoneDesc = "Das Konto wurde zu einem Microsoft-Konto migriert. Bitte melde dich mit Microsoft an."
unreachableTitle = "Fehler bei der Anmeldung:<br>Nicht erreichbar"
unreachableDesc = "Authentifizierungsserver nicht erreichbar. Stelle sicher, dass sie online sind und du mit dem Internet verbunden bist."
gameNotPurchasedTitle = "Fehler bei der Anmeldung:<br>Spiel nicht gekauft"
gameNotPurchasedDesc = "Das Konto, mit dem du dich anmelden möchtest, hat keine Minecraft-Kopie gekauft. Du kannst eine Kopie auf <a href=\"https://minecraft.net/\">Minecraft.net</a> erwerben."
unknownErrorTitle = "Unbekannter Fehler bei der Anmeldung"
unknownErrorDesc = "Ein unbekannter Fehler ist aufgetreten. Bitte siehe Konsole für Details."
